//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smallclinicMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class token_details
    {
        public int TokenID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Specialization { get; set; }
        public string PatientName { get; set; }
        public Nullable<System.DateTime> TokenDate { get; set; }
        public string UniqueToken { get; set; }
    }
}
